package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	"fmt"

	"github.com/HEEPOKE/fiber-graphql/internals/domains/generated"
	"github.com/HEEPOKE/fiber-graphql/internals/domains/generated/model"
	"github.com/HEEPOKE/fiber-graphql/internals/domains/models"
)

// ID is the resolver for the id field.
func (r *accountResolver) ID(ctx context.Context, obj *models.Account) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// Role is the resolver for the role field.
func (r *accountResolver) Role(ctx context.Context, obj *models.Account) (model.Role, error) {
	panic(fmt.Errorf("not implemented: Role - role"))
}

// Account returns generated.AccountResolver implementation.
func (r *Resolver) Account() generated.AccountResolver { return &accountResolver{r} }

type accountResolver struct{ *Resolver }
