package resolvers

// This file will be automatically regenerated based on the schema, any resolver implementations
// will be copied through when generating and any unknown code will be moved to the end.
// Code generated by github.com/99designs/gqlgen version v0.17.45

import (
	"context"
	"fmt"

	"github.com/HEEPOKE/fiber-graphql/internals/domains/generated"
	"github.com/HEEPOKE/fiber-graphql/internals/domains/models"
)

// ID is the resolver for the id field.
func (r *blogResolver) ID(ctx context.Context, obj *models.Blog) (string, error) {
	panic(fmt.Errorf("not implemented: ID - id"))
}

// AccountID is the resolver for the accountId field.
func (r *blogResolver) AccountID(ctx context.Context, obj *models.Blog) (string, error) {
	panic(fmt.Errorf("not implemented: AccountID - accountId"))
}

// Blog returns generated.BlogResolver implementation.
func (r *Resolver) Blog() generated.BlogResolver { return &blogResolver{r} }

type blogResolver struct{ *Resolver }
